### ISSUE TITLE
角色重复问题

### ISSUE THREAD

**Issue by guo323** [lxmghct/user-role-admin#20]
存在一个用户既是“超级管理员”又是“管理员”又是“普通用户”的情况，建议进行修改，使多个角色标签不可共用于同一个用户
![IMG_20240827_103701](https://github.com/user-attachments/assets/e60f3ca1-bb4f-4e8b-b916-52df7e2089b9)
![68b7df55-6587-404e-834c-67889a4261fd_edit_6464193](https://github.com/user-attachments/assets/e2042293-b52c-4524-9904-d94c2a2bd621)
修改：仅适用于所有角色都不可兼容的情况下
![eb910ec8-5179-4d5e-8bbe-e582a127d8f3_edit_6912904](https://github.com/user-attachments/assets/658edc17-6c96-44e2-987e-5257ca05b147)
效果
![8e186967-937a-4b70-82e0-04b40225f2e1_edit_7001497](https://github.com/user-attachments/assets/da7f22d9-d6c3-4270-bb0e-f12516ba311f)

**Comment by lxmghct** [comment]
本项目使用RBAC模型，用户与角色之间可以多对多的关系。
